import Head from 'next/head'
import Link from 'next/link'
import Message from '../components/message'
import { useEffect, useState } from 'react'
import { db } from '../utils/firebase'
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore'

export default function Home() {

  const [allPosts, setAllPosts] = useState([])

  const getPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
    return unsubscribe;
  };

  useEffect(() => {
    getPosts();
  }, [])

  return (
    <div>
      <Head>
        <title>ThoughtSpot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='my-12 text-lg font-medium'>
        <h2 className='pt-2'>See what other people are saying</h2>
        {allPosts.map((post) => (
          <Message key={post.id} {...post}>
            <Link href={{ pathname: `/${post.id}`, query: post }} >
              <button className='flex flex-row items-center bg-white'>
                <img src="https://img.icons8.com/stickers/30/000000/comments--v1.png" className='bg-white' />
                ({post.comments?.length > 0 ? post.comments?.length : 0})
              </button>
            </Link>
          </Message>
        ))}
      </div>

    </div>
  )
}
